name: Continuous Integration

on:
  pull_request:

jobs:
  ci:
    env:
      CARGO_TERM_COLOR: always
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: black-desk/workflows/common@master

      - uses: black-desk/workflows/rust@master