name: Lint Self

on:
  push:
  pull_request:

jobs:
  lint-self:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: 'Lint: black-desk/clean'
        uses: ./
