name: Continuous integration for master

on:
  push:
    branches:
      - master

jobs:
  generic:
    runs-on: ubuntu-latest
    steps:
      - uses: black-desk/workflows/generic@master

  rust:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: black-desk/workflows/rust@master

  build:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - uses: black-desk/workflows/container@master
        with:
          GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
