name: Continuous integration for master

on:
  schedule:
    - cron: 0 0 * * 0
  push:
    branches:
      - master

jobs:
  generic:
    runs-on: ubuntu-latest
    steps:
      - uses: black-desk/workflows/generic@master

  rust:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: black-desk/workflows/rust@master

  container:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - uses: black-desk/workflows/container@master
        with:
          docker__build-push-action__push: true
